[package]
authors = ["am0d"]
name = "rocket-test"
version = "0.1.0"

[dependencies]
dotenv = "0.10.0"
r2d2 = "0.7.2"
r2d2-diesel = "0.13.0"
rocket = "0.2.8"
rocket_codegen = "0.2.8"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[dependencies.clippy]
optional = true
version = "*"

[dependencies.diesel]
features = ["postgres"]
version = "0.13.0"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "0.13.0"

[dependencies.rocket_contrib]
default-features = false
features = ["handlebars_templates"]
version = "0.2.8"
