[package]
authors = ["am0d"]
name = "rocket-test"
version = "0.1.0"

[dependencies]
clippy = {version = "*", optional = true}
diesel = {version="0.13.0", features=["postgres"]}
diesel_codegen = {version = "0.13.0", features = ["postgres"]}
dotenv = "0.10.0"
rocket = "0.2.8"
rocket_codegen = "0.2.8"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[dependencies.rocket_contrib]
default-features = false
features = ["handlebars_templates"]
version = "0.2.8"
